eval:
  seed: 42
  gpu_id: 0
  debug: False
  output_dir: results

task:
  name: xor
  max_steps: 1
  batch_size: 128
  dataset_size: 1024

neat:
  pop_size: 150
  c1: 1.0
  c2: 1.0
  c3: 0.4
  prob_add_node: 0.05
  prob_add_connection: 0.3
  compatibility_threshold: 3.0
  survival_threshold: 0.25
  max_stagnation: 15

trainer:
  n_repeats: 1
  n_evaluations: 1
  max_iter: 100
  test_interval: 10
  log_interval: 100
  use_backprop: True
  backprop_steps: 100
  learning_rate: 0.1
  l2_penalty: 0.001
  complexity_penalty: 0.000
  optimizer: adam

hydra:
  run:
    dir: .                     # Set the working directory to the current directory
  output_subdir: null          # Do not use an output subdirectory
